services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile.mongo
    container_name: test-container-mongo
    networks:
      - test-network
    volumes:
      - mongo-data:/data/db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: test-container-nginx
    ports:
      - "8080:80"
    networks:
      - test-network

  python-api:
    build:
      context: ./microservices/python
      dockerfile: Dockerfile.python
    container_name: test-container-python
    networks:
      - test-network

  php-api:
    build:
      context: ./microservices/php
      dockerfile: Dockerfile.php
    container_name: test-container-php
    networks:
      - test-network

  # java-api:
  #   build:
  #     context: ./microservices/java
  #     dockerfile: Dockerfile.java
  #   container_name: test-container-java
  #   networks:
  #     - test-network

networks:
  test-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local